### PR TITLE
Not clear cart when processing the order payment

### PR DESCRIPTION
**Pull request by ihsanberahim**
solve #14

### CODE REVIEW

**Comment by abdusfauzi** [comment]
I believe simply removing the line will cause confusion. Perhaps, we run the `empty cart` IF the payment process is a `success`?

**Comment by ihsanberahim** [comment]
Woocommerge generally use method `process_payment` to process payment and return `result` and `redirect`. The rest could handle in return and cancel page.

Can refer how woocommerce implement paypal payment gateway.
https://github.com/woocommerce/woocommerce/blob/18ff3960b7413205cc2c725a1310cae1abb0c498/includes/gateways/paypal/class-wc-gateway-paypal.php#L321

**Comment by ihsanberahim** [comment]
it is not critical. Sorry. Could ignore this.

**Comment by abdusfauzi** [comment]
@ihsanberahim no worry. It is great that you pointed out something that others might overlooked. Do you mean that, the cart will definitely cleared out after the redirect to success page? It has been a while since I play around WooCommerce.

This repo is managed by single user, and he might have overlooked certain update/configuration to WooCommerce.

:)

**Comment by ihsanberahim** [comment]
I love billplz, i just try to contribute somewhere.

**Pull request closed without merging**
